### ISSUE TITLE
Configure output path in the GUI

### ISSUE THREAD

**Issue by jza201** [jza201/frdr-secure-data#14]
Output path should be configurable in the GUI, it's already configurable in the CLI, we need to figure out if it belongs in the main window or in a confirmation dialog. I prefer to make another input field in the main window.

**Comment by axfelix** [comment]
I'm not convinced this shouldn't go in a confirmation dialog or a separate prompt -- I think picking "input path" and "output path" in the same window as though they're of equal weight is an uncommon UX pattern and might confuse users.

**Comment by jza201** [comment]
Okay, that makes sense. So we could open a file explorer to select the path after the users click the "Encrypt" submit button, like what you did in moveit?

**Comment by axfelix** [comment]
Yeah, I think we'd probably want to prompt the way we currently prompt for granting access, in order to explicitly say "Please select an output path for the encrypted package," so we don't *just* pop up the file explorer without explanation, but I think walking them through it that way makes more sense than adding another field on the main window.
