### ISSUE TITLE
Add a fourth menu item for users to be able to review all of their existing shares to be able to revoke permissions

### ISSUE THREAD

**Issue by jza201** [jza201/frdr-secure-data#17]
We should add a fourth menu item for users to be able to review all of their existing shares to be able to revoke permissions. This will avoid them ever having to load the Vault UI to review permissions -- probably a good idea as we're handling all of the other interactions in the client.

Right now there's no expiry date for the granted access, we should display this in the fourth menu in the client.

**Comment by axfelix** [comment]
Adding expiry dates will be a separate issue as we'll need to add more functionality to the Vault server app for this (it *may* be worth actually writing a plugin in Go, depending on what you're most excited about, rather than writing a wrapper), but for now adding a menu that can list existing shares and revoke them is a good idea and shouldn't depend on expiration functionality.

**Comment by jza201** [comment]
Do we want to pop up a new window to show all the existing shares? I've added a forth menu to allow users to log into vault. After clicking the "Review Shares" button, I am thinking to create a new window to show the results. And next to each record, display a "revoke access" button. Does this make sense?
![image](https://user-images.githubusercontent.com/26235948/85442818-70ea5e00-b545-11ea-8f9b-adfabad6c8d6.png)

**Comment by axfelix** [comment]
Yeah, I think this makes sense, thanks. For now I don't think we need any other API action than "revoke," either, so it can be a single button for each one ...

**Comment by axfelix** [comment]
Also, with respect to writing a Vault plugin rather than a wrapper for handling permission expiry -- it seems from the documentation that there are only two categories of Vault plugins, "secrets engines" and "auth methods" -- https://learn.hashicorp.com/vault/developer/plugin-backends

It might be possible to create a full fork of one of the simple secrets engines we're using and call it `basic-with-expiry` or something like that but I'm not sure how many maintainability issues that might introduce -- whether we can have the existing code as a dependency or whether we need to maintain a full copy of all the functionality in a separate plugin.

**Comment by jza201** [comment]
I am excited to learn Go! I will take a look at the tutorial if we can develop a plugin that meets our need. In our case, granting permission is by adding users to specific groups. From my understanding, expiry might be just for the secrets in Vault. I guess that I will spend some time on investigating on the Vault plugin development first.
