### ISSUE TITLE
Confirmation dialogs, especially for decrypting and granting access

### ISSUE THREAD

**Issue by axfelix** [jza201/frdr-secure-data#4]
Given the sensitivity of the actions that this client can perform, especially access granting and to a lesser degree decrypting of datasets, we should pop up a confirmation window when users try to perform this action, very clearly spelling out the requester name and the dataset they are being granted access to, and prompt them for confirmation.

We should probably do this in the CLI version as well actually, pretty-printing a bunch of asterisks to format the request as important (similar to when you try to ssh to a server that fails host key validation in your `.ssh/known_hosts` file), prompting for a Y/N before proceeding.

For encrypting, I don't think we need a confirmation dialog, but we should probably have a way of linking users to documentation afterward explaining how to move forward with the deposit process using FRDR and Globus. We should also open the directory containing the encrypted package on their desktop so they can see it (Electron makes it pretty easy to just trigger the default file explorer this way).

**Comment by jza201** [comment]
Do we want to show the requester name or id in the confirmation page? Since the inputs are requester uuid and dataset uuid, if we want to show the requester name, we need to grant depositor access to read info of any user on Vault. It indeed makes more sense to show the requester name, as it seems hard for the depositor to confirm a message like "are you sure to grant requester 4b3d7807-91e6-47f6-bf09-120998cd340a  access to the the dataset 9d32d549-69ac-8685-8abb-bc10b9bc31c4?". Even though, we can get the requester name, still cannot obtain the dataset name because we don't save it to Vault.

**Comment by axfelix** [comment]
Yeah, I think we need to show name -- and it makes sense that we'd have to grant access to read user info to all depositors. I think researcher name + dataset ID is acceptable.

**Comment by jza201** [comment]
Sure, no problem on showing the name. I've added a new function `get_entity_name` in python script, which will be invoked first to get the requester's name after depositor clicks on the "Grant Access" button. I am thinking that this function is supposed to return the name and pass this name to the option of the showMessageBox, so that a message including the requester name will be displayed in the confirmation dialog. I have something like this, but it's not working. Is it possible to return a value from this invoke function, and how to make it work? I am not very clear how this `client.invoke()` works, could not find a good explanation online.
```
var requesterName = null;
client.invoke("get_entity_name", username, password, hostname, requesterID, function(error, res, more) {
    requesterName = res;
});
var options = {
    type: "question",
    buttons: ["Yes", "Cancel"],
    defaultId: 1,
    title: "Confirmation",
    message: "Are you sure to grant access to " + requesterName
}
const response = dialog.showMessageBox(options);
```

**Comment by axfelix** [comment]
yeah, definitely possible to return values, here's a working example:

```
function get_root_dir() {
  client.invoke("get_rootdir", function(error, res, more) {
    document.getElementById("rootdir").setAttribute('value', res)
  });
}
```

```
def get_rootdir(self):
    with open(configjson) as json_file:
        data = json.load(json_file)
    return data['project1']['rootdir']
```

Nothing looks wrong with that javascript to me, what does your Python look like?

**Comment by jza201** [comment]
My python function is
```
 def get_entity_name(self, username, password, hostname, entity_id):
    vault_client = VaultClient(hostname, username, password, tokenfile)
    return vault_client.read_entity_by_id(entity_id)
```
I've pushed my current code to branch `4-add-confirmation-dialog`. I've changed the python function `get_entity_name` to always return a value, so you don't need a running Vault to test the GUI code. 

With `var requesterName = null;` declared, the dialog is always showing null for the requester name. But when I printed the vaule of the requester name, it's actually what is returned from the python function. I also tried removed `var requesterName = null;`, then clicking the `Grant Access` button does not pop up the confirmation window, clicking it again will show the dialog we want. I am so confused.

**Comment by axfelix** [comment]
I think it's probably something to do with variable scope -- you could try this instead:

```
if (res) {
var options = {
    type: "question",
    buttons: ["Yes", "Cancel"],
    defaultId: 1,
    title: "Confirmation",
    message: "Are you sure to grant access to " + res
}
}
```

**Comment by jza201** [comment]
It works this way! Thanks!
